// Global using directives

global using System.Globalization;
global using System.IO.Compression;
global using System.Text.Json;
global using System.Threading.Channels;
global using CsvHelper;
global using CsvHelper.Configuration;
global using JasperFx.CodeGeneration;
global using JasperFx.CodeGeneration.Commands;
global using JasperFx.Core;
global using Metadata.Extensions;
global using Metadata.Features.ClearExistingImdbData;
global using Metadata.Features.Configuration;
global using Metadata.Features.DeleteDownloadedImdbData;
global using Metadata.Features.DownloadImdbData;
global using Metadata.Features.Files;
global using Metadata.Features.ImportImdbData;
global using Metadata.Features.IndexImdbData;
global using Metadata.Features.Jobs;
global using Metadata.Features.Literals;
global using Microsoft.AspNetCore.Builder;
global using Microsoft.Extensions.DependencyInjection;
global using Microsoft.Extensions.DependencyInjection.Extensions;
global using Npgsql;
global using NpgsqlTypes;
global using Oakton;
global using Serilog;
global using Wolverine;
